### ISSUE TITLE
factseg

### ISSUE THREAD

**Issue by twsha** [csliujw/JavaEE-ML#2]
你好，我看你在factseg这篇论文的作者下面留了有关训练问题的言，我可以咨询一下你有关这篇源码的训练问题吗，或者你能给个其他的联系方式吗，谢谢大佬

**Comment by csliujw** [comment]
你好，我并没有跑过 factseg 这篇论文的代码。我跑的是该作者的另一篇论文（LoveDA）的代码。

**Comment by twsha** [comment]
好的谢谢
